# tasks file for rsync-sync
---
- name: "rsync-sync | Install dependencies"
  package:
    name: "{{ item }}"
    state: "{{ pkg_install_state | default('latest') }}"
    update_cache: true
  with_items: "{{ rsync_sync_dependencies }}"
  tags:
    - rsync-sync-dependencies

- name: "rsync-sync | Stat directories"
  stat:
    path: "{{ item }}/"
  register: _stat_directories
  with_items:
    - "{{ rsync_sync_required_paths }}"
  tags:
    - rsync-sync-configure-directories
    - rsync-sync-configure-directories-stat

- name: "rsync-sync | Create directories"
  file:
    path: "{{ item.item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ _stat_directories.results }}"
  when: item.stat is defined and item.stat.exists == false
  tags:
    - rsync-sync-configure-directories
    - rsync-sync-configure-directories-create

- name: "rsync-sync | Generate script(s)"
  template:
    src: usr/local/bin/rsync-sync.j2
    dest: "{{ rsync_sync_install_path }}/{{ item.key }}"
    owner: root
    group: root
    mode: 0755
    validate: '/usr/bin/env bash -n %s'
  with_dict: "{{ rsync_sync_scripts }}"
  tags:
    - rsync-sync-configure
    - rsync-sync-configure-scripts

- name: "rsync-sync | Generate x-from file(s)"
  template:
    src: "{{ rsync_sync_configuration_path.lstrip('/') }}/x-from.j2"
    dest: "{{ rsync_sync_configuration_path }}/{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ rsync_sync_x_from_files }}"
  tags:
    - rsync-sync-configure
    - rsync-sync-configure-x-from-files

- name: "rsync-sync | Configure (cron) jobs"
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    day: "{{ item.day | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    minute: "{{ item.minute | default('*') }}"
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    cron_file: rsync-sync
    user: root
  with_items: "{{ rsync_sync_jobs }}"
  tags:
    - rsync-sync-configure
    - rsync-sync-configure-jobs
