---
- name: 'INIT | Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/os_family/{{ ansible_os_family }}.yml"
  tags:
    - configuration
    - rsync-sync

- name: "TASK | Install rsync"
  import_tasks: install.yml
  tags:
    - configuration
    - rsync-sync
